In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
train_df = pd.read_excel(r"D:\ML_Files\Data_Train.xlsx")
train_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [4]:
test_df = pd.read_excel(r"D:\ML_Files\Test_set.xlsx")
test_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info
0,Jet Airways,6/06/2019,Delhi,Cochin,DEL → BOM → COK,17:30,04:25 07 Jun,10h 55m,1 stop,No info
1,IndiGo,12/05/2019,Kolkata,Banglore,CCU → MAA → BLR,06:20,10:20,4h,1 stop,No info
2,Jet Airways,21/05/2019,Delhi,Cochin,DEL → BOM → COK,19:15,19:00 22 May,23h 45m,1 stop,In-flight meal not included
3,Multiple carriers,21/05/2019,Delhi,Cochin,DEL → BOM → COK,08:00,21:00,13h,1 stop,No info
4,Air Asia,24/06/2019,Banglore,Delhi,BLR → DEL,23:55,02:45 25 Jun,2h 50m,non-stop,No info

In [5]:
df = pd.concat([train_df, test_df], ignore_index=True)
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0

In [6]:
## Fetaure Engineering Process
df['Date'] = df['Date_of_Journey'].str.split('/').str[0]
df['Month'] = df['Date_of_Journey'].str.split('/').str[1]
df['Year'] = df['Date_of_Journey'].str.split('/').str[2]

In [7]:
## OR
df["Date"] = df['Date_of_Journey'].apply(lambda x:x.split("/")[0])
df["Month"] = df['Date_of_Journey'].apply(lambda x:x.split("/")[1])
df["Year"] = df['Date_of_Journey'].apply(lambda x:x.split("/")[2])

In [8]:
df['Date'] = df['Date'].astype(int)
df['Month'] = df['Month'].astype(int)
df['Year'] = df['Year'].astype(int)

In [9]:
df.drop('Date_of_Journey',axis=1 , inplace=True)

In [10]:
df['Arrival_Time']=df['Arrival_Time'].apply(lambda x: x.split(' ')[0])

In [11]:
df['Arrival_Hour']=df['Arrival_Time'].apply(lambda x: x.split(':')[0])
df['Arrival_Minutes']=df['Arrival_Time'].apply(lambda x: x.split(':')[1])

In [12]:
df['Arrival_Hour'] = df['Arrival_Hour'].astype(int)
df['Arrival_Minutes'] = df['Arrival_Minutes'].astype(int)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Dep_Time         13354 non-null  object
 5   Arrival_Time     13354 non-null  object
 6   Duration         13354 non-null  object
 7   Total_Stops      13353 non-null  object
 8   Additional_Info  13354 non-null  object
 9   Price            10683 non-null  float64
 10  Date             13354 non-null  int64
 11  Month            13354 non-null  int64
 12  Year             13354 non-null  int64
 13  Arrival_Hour     13354 non-null  int64
 14  Arrival_Minutes  13354 non-null  int64
dtypes: float64(1), int64(5), object(9)
memory usage: 1.5+ MB

In [14]:
df.drop('Arrival_Time',axis=1,inplace=True)

In [15]:
# Same for departure time


# The .str accessor is excellent for vectorized string operations
# It safely handles nulls without raising an error
df['Dep_Time_Hour'] = df['Dep_Time'].str.split(':').str[0]
df['Dep_Time_Minutes'] = df['Dep_Time'].str.split(':').str[1]

# Now, convert to numeric type. pd.to_numeric() with errors='coerce' is a robust way.
# It will convert non-numeric strings (e.g., '15 ', '10.0') to NaN.
df['Dep_Time_Hour'] = pd.to_numeric(df['Dep_Time_Hour'], errors='coerce')
df['Dep_Time_Minutes'] = pd.to_numeric(df['Dep_Time_Minutes'], errors='coerce')

# Now that the data is numeric, you can safely fill NaNs (if any) and convert to integer.
# It's common to fill NaNs with 0, but this depends on your data context.
df['Dep_Time_Hour'] = df['Dep_Time_Hour'].fillna(0).astype(int)
df['Dep_Time_Minutes'] = df['Dep_Time_Minutes'].fillna(0).astype(int)

# Finally, drop the original column
df.drop('Dep_Time', axis=1, inplace=True)

In [16]:
df['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [17]:
df['Duration_Hour']=df['Duration'].str.split(' ').str[0].str.split('h').str[0]

In [18]:
df[df['Duration_Hour']=='5m']

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Dep_Time_Hour,Dep_Time_Minutes,Duration_Hour
6474,Air India,Mumbai,Hyderabad,BOM → GOI → PNQ → HYD,5m,2 stops,No info,17327.0,6,3,2019,16,55,16,50,5m
13343,Air India,Mumbai,Hyderabad,BOM → GOI → PNQ → HYD,5m,2 stops,No info,NaN,12,3,2019,16,55,16,50,5m

In [20]:
stops_map = {
    'non-stop': 0,
    '1 stop': 1,
    '2 stops': 2,
    '3 stops': 3,
    '4 stops': 4,

    np.nan: 2 
}

# 2. Apply the map to the column
df['Total_Stops'] = df['Total_Stops'].map(stops_map)

# 3. Now that the column contains only numbers (and possibly NaNs if a label wasn't mapped),
#    fill any remaining NaNs with a default value, then convert to int.
df['Total_Stops'] = df['Total_Stops'].fillna(2).astype(int)
print(df['Total_Stops'].isnull().sum())

0

In [21]:
df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Dep_Time_Hour,Dep_Time_Minutes,Duration_Hour
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0,No info,3897.0,24,3,2019,1,10,22,20,2
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2,No info,7662.0,1,5,2019,13,15,5,50,7
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2,No info,13882.0,9,6,2019,4,25,9,25,19
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1,No info,6218.0,12,5,2019,23,30,18,5,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1,No info,13302.0,1,3,2019,21,35,16,50,4

In [22]:
#Dropping this row bcz due to this we are not able to convert Duration_Hour to int
# Find the index of the row where 'Duration' is '5m'
index_to_drop = df[df['Duration'] == '5m'].index

# Drop the row using its new index
df.drop(index_to_drop, axis=0, inplace=True)

In [23]:
df['Duration_Hour'] = df['Duration_Hour'].astype(int)

In [24]:
df.drop('Duration',axis=1,inplace=True)

In [25]:
df.head()

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Dep_Time_Hour,Dep_Time_Minutes,Duration_Hour
0,IndiGo,Banglore,New Delhi,BLR → DEL,0,No info,3897.0,24,3,2019,1,10,22,20,2
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2,No info,7662.0,1,5,2019,13,15,5,50,7
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2,No info,13882.0,9,6,2019,4,25,9,25,19
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1,No info,6218.0,12,5,2019,23,30,18,5,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1,No info,13302.0,1,3,2019,21,35,16,50,4

In [26]:
df['Airline'].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [27]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

df['Airline'] = labelencoder.fit_transform(df['Airline'])
df['Source'] = labelencoder.fit_transform(df['Source'])
df['Destination'] = labelencoder.fit_transform(df['Destination'])
df['Additional_Info'] = labelencoder.fit_transform(df['Additional_Info'])

In [28]:
#I used prefix='Destination' when demonstrating one-hot encoding with pd.get_dummies() for a specific reason.
#The prefix parameter adds a string prefix to the new binary columns that are created. For example, if your original column is named 'Destination' and its unique categories are 'Banglore', 'New Delhi', and 'Cochin', using prefix='Destination' will result in new columns named:
#Destination_Banglore
#Destination_New Delhi
#Destination_Cochin

In [29]:
destination_dummies = pd.get_dummies(df['Destination'], prefix='Destination', drop_first=True)
df = pd.concat([df, destination_dummies], axis=1)

In [30]:
df.drop('Destination', axis=1, inplace=True)

In [31]:
df.head(20)

,Airline,Source,Route,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Dep_Time_Hour,Dep_Time_Minutes,Duration_Hour,Destination_1,Destination_2,Destination_3,Destination_4,Destination_5
0,3,0,BLR → DEL,0,8,3897.0,24,3,2019,1,10,22,20,2,False,False,False,False,True
1,1,3,CCU → IXR → BBI → BLR,2,8,7662.0,1,5,2019,13,15,5,50,7,False,False,False,False,False
2,4,2,DEL → LKO → BOM → COK,2,8,13882.0,9,6,2019,4,25,9,25,19,True,False,False,False,False
3,3,3,CCU → NAG → BLR,1,8,6218.0,12,5,2019,23,30,18,5,5,False,False,False,False,False
4,3,0,BLR → NAG → DEL,1,8,13302.0,1,3,2019,21,35,16,50,4,False,False,False,False,True
5,8,3,CCU → BLR,0,8,3873.0,24,6,2019,11,25,9,0,2,False,False,False,False,False
6,4,0,BLR → BOM → DEL,1,5,11087.0,12,3,2019,10,25,18,55,15,False,False,False,False,True
7,4,0,BLR → BOM → DEL,1,8,22270.0,1,3,2019,5,5,8,0,21,False,False,False,False,True
8,4,0,BLR → BOM → DEL,1,5,11087.0,12,3,2019,10,25,8,55,25,False,False,False,False,True
9,6,2,DEL → BOM → COK,1,8,8625.0,27,5,2019,19,15,11,25,7,True,False,False,False,False
10,1,2,DEL → BLR → COK,1,8,8907.0,1,6,2019,23,0,9,45,13,True,False,False,False,False
11,3,3,CCU → BLR,0,8,4174.0,18,4,2019,22,55,20,20,2,False,False,False,False,False
12,1,1,MAA → CCU,0,8,4667.0,24,6,2019,13,55,11,40,2,False,False,False,True,False
13,4,3,CCU → BOM → BLR,1,5,9663.0,9,5,2019,9,20,21,10,12,False,False,False,False,False
14,3,3,CCU → BLR,0,8,4804.0,24,4,2019,19,50,17,15,2,False,False,False,False,False
15,1,2,DEL → AMD → BOM → COK,2,8,14011.0,3,3,2019,19,15,16,40,26,True,False,False,False,False
16,8,2,DEL → PNQ → COK,1,8,5830.0,15,4,2019,13,15,8,45,4,True,False,False,False,False
17,4,2,DEL → BOM → COK,1,5,10262.0,12,6,2019,12,35,14,0,22,True,False,False,False,False
18,1,2,DEL → CCU → BOM → COK,2,8,13381.0,12,6,2019,19,15,20,15,23,True,False,False,False,False
19,4,2,DEL → BOM → COK,1,5,12898.0,27,5,2019,12,35,16,0,20,True,False,False,False,False

In [32]:
boolean_to_int_map = {True: 1, False: 0}

# Select all the one-hot encoded columns
new_destination_columns = [col for col in df.columns if col.startswith('Destination_')]
df[new_destination_columns] = df[new_destination_columns].apply(
    lambda col: col.map(boolean_to_int_map)
)

In [33]:
df.head()

,Airline,Source,Route,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Dep_Time_Hour,Dep_Time_Minutes,Duration_Hour,Destination_1,Destination_2,Destination_3,Destination_4,Destination_5
0,3,0,BLR → DEL,0,8,3897.0,24,3,2019,1,10,22,20,2,0,0,0,0,1
1,1,3,CCU → IXR → BBI → BLR,2,8,7662.0,1,5,2019,13,15,5,50,7,0,0,0,0,0
2,4,2,DEL → LKO → BOM → COK,2,8,13882.0,9,6,2019,4,25,9,25,19,1,0,0,0,0
3,3,3,CCU → NAG → BLR,1,8,6218.0,12,5,2019,23,30,18,5,5,0,0,0,0,0
4,3,0,BLR → NAG → DEL,1,8,13302.0,1,3,2019,21,35,16,50,4,0,0,0,0,1